Add Prometheus JMX Exporter
camunda/docker-camunda-bpm-platform pull request #105
Opened 2019-09-24 16:29 UTC by ihostage

Inspired by https://blog.camunda.com/post/2019/06/camunda-bpm-on-kubernetes/

2019-09-24 16:40 UTC, ihostage commented
Also, indentation unified for some scripts by the rule of a boy scout. 😄

2019-09-27 10:09 UTC, cmur2 requested changes
Thank you for your tremendously well made and valuable contribution! I like the overall idea and I'm sure it is the right tradeoff to include the JMX Prometheus Agent in terms of space and number of dependencies vs out-of-the-box usability :+1:

I also appreciate that you contribute suitable and mindful tests for this feature, definitively eases maintenance.

In the comments I would like to see one nitpicky thing changed and I'm currently also testing this on CI against EE edition to make sure it's green.

2019-09-27 10:09 UTC, cmur2 commented on Dockerfile
> +ENV JMX_PROMETHEUS_CONF=/camunda/javaagent/prometheus-jmx.yaml
It is a bit nitpicky but I'd like to canonicalise the `.yaml` extension to `.yml` as we try to do in all our systems.

2019-09-27 10:09 UTC, cmur2 commented on README.md
> +at `/camunda/javaagent/prometheus-jmx.yaml`.
Extension again

2019-09-27 10:24 UTC, ihostage commented on Dockerfile
> +ENV JMX_PROMETHEUS_CONF=/camunda/javaagent/prometheus-jmx.yaml
Done 😉

2019-09-27 10:24 UTC, ihostage commented on README.md
> +at `/camunda/javaagent/prometheus-jmx.yaml`.
Done 😉

2019-09-27 10:26 UTC, cmur2 approved these changes

2019-09-27 10:40 UTC, cmur2 commented
I will merge as soon as https://travis-ci.com/camunda/docker-camunda-bpm-platform/builds/129427442 goes green.

2019-09-27 10:48 UTC, merged

2019-09-27 10:49 UTC, ihostage commented
Thank a lot, @cmur2 :+1: 
May be can you review my other PR? 😄

2019-09-27 10:50 UTC, cmur2 commented
It's internally assigned to another team member who will have a look at it but it wont be forgotten :+1: