feat(docker): add arm64 build
camunda/docker-camunda-bpm-platform pull request #237
Opened 2022-11-16 11:31 UTC by danielkelemen

2022-11-21 18:09 UTC, mleiter06 commented
watching!

2022-11-28 20:29 UTC, bstncartwright approved these changes

2023-01-04 16:06 UTC, tasso94 requested changes
Looks good to me in general. I added some hints/questions below.

2023-01-04 16:06 UTC, tasso94 commented on release.sh
> +        --build-arg PASSWORD=${NEXUS_PASS}        \
Can you check if the credentials are retrievable via docker history? If yes, that would be problematic.
Cf. https://stackoverflow.com/a/68187363

2023-01-04 16:06 UTC, tasso94 commented on pipeline.sh
> +docker inspect "${IMAGE_NAME}" | grep "Architecture" -A2
Sweet.

2023-01-04 16:06 UTC, tasso94 commented on .github/workflows/build-test-and-publish-ce.yml
> +        uses: crazy-max/ghaction-github-runtime@v2
Do we really want to add a dependency to `crazy-max/ghaction-github-runtime@v2` that has only 19 stars and does something relatively simple? Can we just pass the GitHub Runtime environment variables we need to the build/release step? This makes also more transparent where things come from.

2023-01-04 16:20 UTC, tasso94 commented
When I search for the JRE `openjdk11-jre-headless` that is used inside the image in the Alpine package registry, I cannot find an ARM variant of it. How does this actually work? If it's emulated, should we move to an ARM-native JRE instead? Can you also check the other packages?
https://github.com/camunda/docker-camunda-bpm-platform/blob/ff7f677a0ab9d280893a03fee3507e19c5055693/Dockerfile#L61-L68

2023-01-04 16:29 UTC, danielkelemen commented
> When I search for the JRE `openjdk11-jre-headless` [1] that is used inside the image in the Alpine package registry, I cannot find an ARM variant of it. How does this actually work? If it's emulated, should we move to an ARM-native JRE instead? Can you also check the other packages?

That's the [aarch64](https://en.wikipedia.org/wiki/AArch64) package:
```sh
/ # apk add openjdk11-jre-headless
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/aarch64/APKINDEX.tar.gz
(1/8) Installing java-common (0.5-r0)
...
```
I guess it's also the one installed for the arm/v6 and arm/v7 packages because alpine has those variants too.

2023-01-04 16:36 UTC, danielkelemen commented on .github/workflows/build-test-and-publish-ce.yml
> +        uses: crazy-max/ghaction-github-runtime@v2
It's crazy-max! 😄
I'll refactor it...

2023-01-09 15:32 UTC, danielkelemen commented on release.sh
> +        --build-arg PASSWORD=${NEXUS_PASS}        \
Link to the same question: https://github.com/camunda/jenkins-job-dsl-seed-jobs/pull/380#discussion_r1064768499

2023-01-10 09:39 UTC, tasso94 approved these changes

2023-01-10 10:19 UTC, merged