wait-for-it / handle several databases if needed (primary/secondary/etc)
camunda/docker-camunda-bpm-platform pull request #278
Opened 2023-07-27 14:18 UTC by nesies

Fixes #3555

If you specify several database in your JDBC_URL, you might want to start if at latest on of them is responding.

https://github.com/camunda/camunda-bpm-platform/issues/3555

2023-07-28 07:21 UTC, tasso94 commented
Hi @nesies,

Thank you for your pull request.

My colleague @yanavasileva will look into it after the summer break.

Stay tuned!

Best,
Tassilo

2023-08-25 10:38 UTC, yanavasileva requested changes
Overall the implementation looks good to me. I added suggestions for the wording in the run script, please consider them for all of the three scripts.
Meantime, I would ask for a second reviewer in case I overlooked something.

2023-08-25 10:38 UTC, yanavasileva commented on camunda-run.sh
> +      echo "$tmp up"
Adjust working to:
```suggestion
      echo "$tmp available"
```

2023-08-25 10:38 UTC, yanavasileva commented on camunda-run.sh
> +      echo "$tmp down"
Adjust working to:
```suggestion
      echo "$tmp not available"
```

2023-08-25 10:38 UTC, yanavasileva commented on camunda-run.sh
> +    echo "nothing up in WAIT_FOR=$WAIT_FOR"
Adjust working to:
```suggestion
    echo "No connection available in WAIT_FOR=$WAIT_FOR"
```

2023-08-25 10:38 UTC, yanavasileva commented on camunda-run.sh
> +  for tmp in $(echo "${WAIT_FOR}" | tr ',' '\n'); do
Adjust the `tmp` variable name to something more meaningful like `currentConnection`.

2023-08-25 10:39 UTC, yanavasileva commented
@tasso94, could you please have a look at this feature request contribution in case I overlooked some aspect.

2023-09-05 12:43 UTC, nesies commented
thanks, i made the changes

2023-09-05 14:08 UTC, tasso94 commented
@yanavasileva, I had a brief look, and here is my input:
* Can we consolidate the code into a single file so that we don't need to change it at multiple places in the future? When fixing something, we might miss changing it everywhere in the future, which is not as maintainable as it could be.
* I haven't checked it in detail, but we must ensure this doesn't change how it previously worked (backwards compatibility). Can you double-check that?

2023-09-13 08:32 UTC, yanavasileva commented
@nesies, thank you for applying the review hints so far.
Could you also consolidate the code into a single file as suggested by tasso94 above?

2023-09-20 15:44 UTC, yanavasileva requested changes
Hi @nesies,

The current implementation is failing and I think a few components are missing:
* ensure the correct name is passed for the "common-lib"
* ensure the file is present when a docker image is created
* test the docker image with the following scenarios:
  * the WAIT_FOR argument not passed
  * WAIT_FOR argument given with one db connection 
  * WAIT_FOR argument given with two or more db connections

2023-09-20 15:44 UTC, yanavasileva commented on camunda-run.sh
> +source $(dirname "$0")/common-lib.sh
source is given `common-lib` but that file is missing, here is the output if I try to run a docker:
`./camunda.sh: line 6: ./common-lib.sh: No such file or directory`

2023-11-15 19:17 UTC, nesies commented on camunda-run.sh
> +source $(dirname "$0")/common-lib.sh
i fixed and tested it, seems to works now.

```
# docker run -it camunda:latest -e WAIT_FOR="1.2.2.2:80 proxy:3128"
wait-for-it.sh: waiting 30 seconds for 1.2.2.2:80
wait-for-it.sh: timeout occurred after waiting 30 seconds for 1.2.2.2:80
1.2.2.2:80 not available
wait-for-it.sh: waiting 30 seconds for proxy:3128
wait-for-it.sh: proxy:3128 is available after 0 seconds
proxy:3128 available
JAVA_HOME is not set. Unexpected results may occur.
Set JAVA_HOME to the directory of your local JDK to avoid this message.
Java version is 17.0.9
...
```

2023-11-16 07:56 UTC, yanavasileva commented on camunda-run.sh
> +source $(dirname "$0")/common-lib.sh
That's great, could you push your changes to the remote branch.

2023-11-16 09:24 UTC, nesies commented on camunda-run.sh
> +source $(dirname "$0")/common-lib.sh
pushed

2023-12-21 08:56 UTC, yanavasileva reviewed
👍 @nesies, looks good. Thank you for implementing our feedback.

Before I merge the request, could you please also adjust the [readme](https://github.com/camunda/docker-camunda-bpm-platform/?tab=readme-ov-file#waiting-for-database) with the new option specifying the syntax when the user passes multiple `host:port` to wait for.

2024-01-03 14:01 UTC, merged

2024-01-03 14:04 UTC, yanavasileva commented
@nesies, I merged the code with (cf15703) after adjusting the readme. The feature will be available with Camunda `7.21` and next `7.21.0-alpha3`. Once again, thank you for the contribution.